name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencie for 32 bits compilation
      run: sudo apt update && sudo apt install libc6-dev-i386

    - name: Run make
      run: make

    - name: clean
      run: make fclean

    - name: test
      run: make test